### ISSUE TITLE
Device discovery looks very fragile

### ISSUE THREAD

**Issue by theHacker** [project-alice-assistant/AliceCLI#3]
Just had a look into `discover()`, because AliceCLI did not display any devices for me.

I found
a) `socket.gethostbyname(socket.gethostname())` just reverses-lookup my hostname, resulting in `127.0.1.1`, a loopback address.
b) AliceCLI then just assumes this is a '/24' net (it is not!) and pings 254 times the (local) machine. All these IPs are pingable, and therefore end up in `devices`.
c) A "potential device" must have "projectalice" or "raspberrypi" inside name.
d) There is a `.home` replacement hack in the code.

There are a couple of suggestions to improve here :)
a)
- I would not only do this approach, but try more ways. For example `ip a` or `hostname -I`. These depend very much on the underlying OS, but so does the current approach with `ping` (there is also a switch between Windows and the rest).
- The user should be able to see, what's happening (display all found nets and let the user choose "My PI is in 192.168.0.0/24", "Just search all found nets" or even provide a text field option "My PI is in neither of the above nets / or not detectable. I would like to type the IP address manually".
Hint: I have Docker installed on my machine, I have 22 different IP addresses/nets on this machine.

b)
- For private IP addresses, there are different nets (see https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses) and they very much depend what the user has configured. I like the idea of an "auto sensible default", but should be changeable by the user.

c)
- I don't like too long hostnames (I have a lot of machines in my network), so I would name my Alice "project-alice" (with a minus sign). Maybe just searching for "alice" or "raspberry" (even "pi" as a word, not just substring).

d)
- For example I use `.thehacker.local` at home :grin: - not sure, whether you should keep this special case.

I have seen, there is the option to explicitly list all device, not just the potential ones, by `alice discover -a`. As also the `--network` option. I get good results, if I use them both. However all the data is displayed twice (on top with IP and hostname, then below in the menu only with IP adress), so it's hard to read. – What about putting both (IP and name) into the menu?

---

Looking forward to feedback on my finding and suggestions. I would be happy to code something and create a PR, but makes sense only, if you like my direction. :smiley:

**Comment by Psychokiller1888** [comment]
All good and fair points!

The reasons it's so fragile are it's been put on place in a couple of hours because some were desperate for an easy way to install and I decided to quickly mash that up. And also because I'm not very up to date when it comes to network :)

**Comment by Psychokiller1888** [comment]
Any news on this?

**Comment by theHacker** [comment]
Sorry, no. I planned to continue looking into Project Alice over Christmas, but I am caught up in something else for now.
(Raspberry is still laying around on the table, so it's not completely forgotten :smile: )
