### ISSUE TITLE
install issue 

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/AliceCLI#7]
Just in case it's something you need to know ? I got the below install errors while trying to update to the latest CLI. feel free to close the issue if it's not something you want to account for :)

>larry@larrys-linux:~$ pip3.8 uninstall projectalice-cli
Found existing installation: projectalice-cli 0.1.3
Uninstalling projectalice-cli-0.1.3:
  Would remove:
    /home/larry/.local/bin/alice
    /home/larry/.local/lib/python3.8/site-packages/AliceCli/*
    /home/larry/.local/lib/python3.8/site-packages/projectalice_cli-0.1.3.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled projectalice-cli-0.1.3
larry@larrys-linux:~$ pip3.8 install projectalice-cli
Defaulting to user installation because normal site-packages is not writeable
Collecting projectalice-cli
  Downloading projectalice_cli-1.1.0-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 405 kB/s            
Collecting coverage~=6.2
  Downloading coverage-6.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (217 kB)
     |████████████████████████████████| 217 kB 17 kB/s            
Collecting beautifulsoup4~=4.10.0
  Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 68 kB/s             
Collecting requests~=2.26.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 40 kB/s            
Collecting InquirerPy~=0.3.1
  Downloading InquirerPy-0.3.1-py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 39 kB/s            
Collecting click~=8.0.3
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 42 kB/s            
Collecting paramiko~=2.8.1
  Downloading paramiko-2.8.1-py2.py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB 20 kB/s            
Collecting tqdm~=4.62.3
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 20 kB/s            
Collecting pytest-cov~=3.0.0
  Downloading pytest_cov-3.0.0-py3-none-any.whl (20 kB)
Requirement already satisfied: networkscan~=1.0.9 in ./.local/lib/python3.8/site-packages (from projectalice-cli) (1.0.9)
Requirement already satisfied: psutil~=5.8.0 in ./.local/lib/python3.8/site-packages (from projectalice-cli) (5.8.0)
Collecting pytest~=6.2.5
  Downloading pytest-6.2.5-py3-none-any.whl (280 kB)
     |████████████████████████████████| 280 kB 18 kB/s            
Collecting pyyaml~=6.0
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     |████████████████████████████████| 701 kB 20 kB/s            
Collecting coveralls~=3.3.1
  Downloading coveralls-3.3.1-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.8/dist-packages (from beautifulsoup4~=4.10.0->projectalice-cli) (2.0.1)
Requirement already satisfied: docopt>=0.6.1 in /usr/local/lib/python3.8/dist-packages (from coveralls~=3.3.1->projectalice-cli) (0.6.2)
Collecting pfzy<0.4.0,>=0.3.1
  Downloading pfzy-0.3.3-py3-none-any.whl (8.5 kB)
Collecting prompt-toolkit<4.0.0,>=3.0.1
  Downloading prompt_toolkit-3.0.24-py3-none-any.whl (374 kB)
     |████████████████████████████████| 374 kB 25 kB/s            
Requirement already satisfied: bcrypt>=3.1.3 in /usr/lib/python3/dist-packages (from paramiko~=2.8.1->projectalice-cli) (3.1.7)
Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko~=2.8.1->projectalice-cli) (2.8)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib/python3/dist-packages (from paramiko~=2.8.1->projectalice-cli) (1.3.0)
Requirement already satisfied: toml in /usr/local/lib/python3.8/dist-packages (from pytest~=6.2.5->projectalice-cli) (0.10.1)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.8/dist-packages (from pytest~=6.2.5->projectalice-cli) (1.1.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from pytest~=6.2.5->projectalice-cli) (20.4)
Requirement already satisfied: py>=1.8.2 in /usr/local/lib/python3.8/dist-packages (from pytest~=6.2.5->projectalice-cli) (1.9.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.8/dist-packages (from pytest~=6.2.5->projectalice-cli) (0.13.1)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.8/dist-packages (from pytest~=6.2.5->projectalice-cli) (20.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests~=2.26.0->projectalice-cli) (2.8)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.10-py3-none-any.whl (39 kB)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests~=2.26.0->projectalice-cli) (2019.11.28)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/lib/python3.8/site-packages (from requests~=2.26.0->projectalice-cli) (1.25.10)
Collecting tomli
  Downloading tomli-2.0.0-py3-none-any.whl (12 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit<4.0.0,>=3.0.1->InquirerPy~=0.3.1->projectalice-cli) (0.2.5)
Requirement already satisfied: six in ./.local/lib/python3.8/site-packages (from packaging->pytest~=6.2.5->projectalice-cli) (1.14.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->pytest~=6.2.5->projectalice-cli) (2.4.7)
Installing collected packages: tomli, coverage, charset-normalizer, requests, pytest, prompt-toolkit, pfzy, tqdm, pyyaml, pytest-cov, paramiko, InquirerPy, coveralls, click, beautifulsoup4, projectalice-cli
  Attempting uninstall: requests
    Found existing installation: requests 2.24.0
    Uninstalling requests-2.24.0:
      Successfully uninstalled requests-2.24.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyinquirer 1.0.3 requires prompt-toolkit==1.0.14, but you have prompt-toolkit 3.0.24 which is incompatible.
projectalice-sk 1.9.5 requires coverage~=4.5.4, but you have coverage 6.2 which is incompatible.
projectalice-sk 1.9.5 requires coveralls~=1.8.2, but you have coveralls 3.3.1 which is incompatible.
projectalice-sk 1.9.5 requires prompt-toolkit==1.0.14, but you have prompt-toolkit 3.0.24 which is incompatible.
projectalice-sk 1.9.5 requires pytest~=5.2.2, but you have pytest 6.2.5 which is incompatible.
projectalice-sk 1.9.5 requires pytest-cov~=2.8.1, but you have pytest-cov 3.0.0 which is incompatible.
mediawikiapi 1.1.5 requires beautifulsoup4==4.9.1, but you have beautifulsoup4 4.10.0 which is incompatible.
Successfully installed InquirerPy-0.3.1 beautifulsoup4-4.10.0 charset-normalizer-2.0.10 click-8.0.3 coverage-6.2 coveralls-3.3.1 paramiko-2.8.1 pfzy-0.3.3 projectalice-cli-1.1.0 prompt-toolkit-3.0.24 pytest-6.2.5 pytest-cov-3.0.0 pyyaml-6.0 requests-2.26.0 tomli-2.0.0 tqdm-4.62.3
larry@larrys-linux:~$

**Comment by Psychokiller1888** [comment]
Mmmmh, the get around is to install in a venv for the time being

**Comment by Psychokiller1888** [comment]
Fixed

**Comment by LazzaAU** [comment]
agreed, installed flawlessly :) cheers
